### ISSUE TITLE
Colonne "menu" dans la liste des modules

### ISSUE THREAD

**Issue by alain01** [GregMage/xmsocial#2]
A l'installation,
Xmsocial ne devrait pas avoir la colonne menu disponible
![Capture d’écran 2021-02-04 233805](https://user-images.githubusercontent.com/5336960/106964229-13a4c500-6742-11eb-8b5b-a04db281cdbd.png)
Ni croix rouge, ni coche verte, 
Cette colonne doit être vide (comme pour le module system)

**Comment by GregMage** [comment]
Pas vraiment, si je désactive la partie user le module ne peut pas fonctionner. Donc pas le choix...

**Comment by alain01** [comment]
Ok mais alors attention dans ce cas avec le lien du module sur le bloc menu principal !

**Comment by GregMage** [comment]
Il semblerait que je n'ai pas besoin d'activer la partie user pour que le module fonctionne!

**Comment by GregMage** [comment]
Ceci pose un gros problème car pour les permission de xoops il est nécessaire d'avoir une partie user. Je n'aurai pas du modifier cela. Je vais donc revenir en arrière.
